apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-app
spec:
  type: NodePort
  selector:
    app: nginx-server
  ports:
    - name: http
      port: 80
      targetPort: 80